version: "3.3"

services:
  sms-db:
    container_name: sms-db
    restart: always
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD:
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./_dbschema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
