version: "3.3"

services:
  db:
    container_name: sms-db
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD:
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./_dbschema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  app:
    container_name: sms-app
    image: php:apache
    build: .
    restart: always
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
